const throwError = () => {
  throw new Error("This is my error 2!!!");
};

export default throwError;
