const throwError = () => {
  throw new Error("This is my error another!!!");
};

export default throwError;
