const throwError = () => {
  throw new Error("This is my error another foo!!!");
};

export default throwError;
